### ISSUE TITLE
BytesField / UnicodeField ?

### ISSUE THREAD

**Issue by dobesv** [six8/springfield#9]
Might want to add field types that specifically use `bytes` or `unicode`.  Or if its more forward-looking to python3, it would just be `StringField` (unicode) and `BytesField`.

**Comment by six8** [comment]
Agreed. Been meaning to do that. I think we just add a `BytesField` and then there's no need for a non-unicode field.

**Comment by dobesv** [comment]
Actually it seems like currently StringField won't work with binary data, any bytes that aren't ASCII will result in a UnicodeDecodeError.

**Comment by six8** [comment]
So `StringField` shouldn't be used for binary.
